// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsc-yUrwGcMpwHt1ZFjb8RWMaNQSBWHFQ',
    appId: '1:816818496236:web:7c12a99fae29e7e3fdfbc9',
    messagingSenderId: '816818496236',
    projectId: 'mindcare-e9b55',
    authDomain: 'mindcare-e9b55.firebaseapp.com',
    storageBucket: 'mindcare-e9b55.firebasestorage.app',
    measurementId: 'G-WX9BKTF59L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEYuiSNhYI15fMErZNxxAtX4ninoyFBbo',
    appId: '1:816818496236:android:ffdff34cc830a569fdfbc9',
    messagingSenderId: '816818496236',
    projectId: 'mindcare-e9b55',
    storageBucket: 'mindcare-e9b55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWbMbB7MxZeC1kHOXFnJJREFn5NJtxUO0',
    appId: '1:816818496236:ios:e64e335912cc1313fdfbc9',
    messagingSenderId: '816818496236',
    projectId: 'mindcare-e9b55',
    storageBucket: 'mindcare-e9b55.firebasestorage.app',
    iosBundleId: 'com.mindcare.perera',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWbMbB7MxZeC1kHOXFnJJREFn5NJtxUO0',
    appId: '1:816818496236:ios:48edabb74910d8b0fdfbc9',
    messagingSenderId: '816818496236',
    projectId: 'mindcare-e9b55',
    storageBucket: 'mindcare-e9b55.firebasestorage.app',
    iosBundleId: 'com.example.mindcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsc-yUrwGcMpwHt1ZFjb8RWMaNQSBWHFQ',
    appId: '1:816818496236:web:90040f1324e902d8fdfbc9',
    messagingSenderId: '816818496236',
    projectId: 'mindcare-e9b55',
    authDomain: 'mindcare-e9b55.firebaseapp.com',
    storageBucket: 'mindcare-e9b55.firebasestorage.app',
    measurementId: 'G-BN3MFYDQ6M',
  );
}
